name: roles
description: A dart package for handling role based authorized function calls
version: 0.0.1
homepage: https://github.com/cookytech/roles
repository: https://github.com/cookytech/roles

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  equatable: ^1.2.5

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
